//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UGE4.Models
{
    public partial class Choice
    {
        public long ChoiceID { get; set; }
        public long QuestionID { get; set; }
        public string ChoiceDisplay { get; set; }
    
        public virtual Question Question { get; set; }
    }
    
}
