//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE4.DbInfrastructure
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleMistakes = new HashSet<ArticleMistake>();
            this.Bookmarks = new HashSet<Bookmark>();
            this.Chapters = new HashSet<Chapter>();
            this.LinksToDisplays = new HashSet<LinksToDisplay>();
            this.MCQs = new HashSet<MCQ>();
            this.Ratings = new HashSet<Rating>();
            this.WatchedReferences = new HashSet<WatchedReference>();
            this.WatchedReferences1 = new HashSet<WatchedReference>();
            this.WishLists = new HashSet<WishList>();
        }
    
        [DisplayName("Article ID")]        
        public long ArticleID { get; set; }
        
        [DisplayName("Article Name")]      
        [StringLength(150)]
        [Required]
        public string ArticleName { get; set; }
        
        [DisplayName("Description")]      
        [StringLength(800)]
        [Required]
        public string Description { get; set; }
        
        [DisplayName("Previous Article ID")]      
        public Nullable<long> PreviousArticleID { get; set; }
        
        [DisplayName("Next Article ID")]      
        public Nullable<long> NextArticleID { get; set; }
        
        [DisplayName("Chapter ID")]      
        public int ChapterID { get; set; }
        
        [DisplayName("Video Embed HTML")]      
        [Required]
        public string VideoLink { get; set; }
        
        [DisplayName("Height")]      
        [Required]
        public short Height { get; set; }
        
        [DisplayName("Width")]      
        [Required]
        public short Width { get; set; }
        [DisplayName("Average Rating")]      
        [Required]
        public double AvgRating { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual ICollection<ArticleMistake> ArticleMistakes { get; set; }
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual ICollection<Chapter> Chapters { get; set; }
        public virtual ICollection<LinksToDisplay> LinksToDisplays { get; set; }
        public virtual ICollection<MCQ> MCQs { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<WatchedReference> WatchedReferences { get; set; }
        public virtual ICollection<WatchedReference> WatchedReferences1 { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
