//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE4.DbInfrastructure
{
    using System;
    using System.Collections.Generic;
      using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ArticleMistake
    {
        public ArticleMistake()
        {
            this.ReplyAgainstMistakes = new HashSet<ReplyAgainstMistake>();
        }
    
        [DisplayName("Article Mistake ID")]      
        public long ArticleMistakeID { get; set; }
        
        [DisplayName("User ID")]      
        [Required]
        public int UserID { get; set; }
        
        [DisplayName("Article ID")]      
        [Required]
        public long ArticleID { get; set; }
        
        [DisplayName("Submited Dated")]      
        [Required]
        public System.DateTime SubmitedDated { get; set; }
    
        [DisplayName("Articles")]      
        public virtual Article Article { get; set; }
        
        [DisplayName("Users")]      
        public virtual User User { get; set; }
            
        [DisplayName("Reply Against Mistakes")]      
        public virtual ICollection<ReplyAgainstMistake> ReplyAgainstMistakes { get; set; }
    }
}
