//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE4.DbInfrastructure
{
    using System;
    using System.Collections.Generic;
      using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Bookmark
    {
        [DisplayName("Bookmark ID")]      
    [StringLength(150)]
    [Required]
public long BookmarkID { get; set; }
        
        [DisplayName("User ID")]      
    [StringLength(150)]
    [Required]
public int UserID { get; set; }
        
        [DisplayName("Article ID")]      
    [StringLength(150)]
    [Required]
public long ArticleID { get; set; }
    
        [DisplayName("Articles")]      
    public virtual Article Article { get; set; }
        
        [DisplayName("Users")]      
    public virtual User User { get; set; }
    }
}
