//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE4.DbInfrastructure
{
    using System;
    using System.Collections.Generic;
      using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Book
    {
        public Book()
        {
            this.Chapters = new HashSet<Chapter>();
        }
    
        [DisplayName("Book ID")]      
        public int BookID { get; set; }
        
        [DisplayName("Subject ID")]      
    [StringLength(150)]
    [Required]
public byte SubjectID { get; set; }
        
        [DisplayName("Book Name")]      
    [StringLength(150)]
    [Required]
public string BookName { get; set; }
    
        
        [DisplayName("Subjects")]      
    [StringLength(150)]
    [Required]
public virtual Subject Subject { get; set; }
        
        [DisplayName("Chapters")]      
    [StringLength(150)]
    [Required]
public virtual ICollection<Chapter> Chapters { get; set; }
    }
}
