//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE4.DbInfrastructure
{
    using System;
    using System.Collections.Generic;
      using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Choice
    {
              [DisplayName("Choice ID")]      
              public long ChoiceID { get; set; }
        
              [DisplayName("Question ID")]      
      [Required]
public long QuestionID { get; set; }
        
              [DisplayName("Choice Display")]      
      [StringLength(500)]
      [Required]
public string ChoiceDisplay { get; set; }
    
              [DisplayName("Questions")]      
      public virtual Question Question { get; set; }
    }
}
