//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE4.DbInfrastructure
{
    using System;
    using System.Collections.Generic;
      using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LinksToDisplay
    {
              [DisplayName("Links To Display ID")]      
      public long LinksToDisplayID { get; set; }
        
              [DisplayName("Article ID")]      
      [Required]
public long ArticleID { get; set; }
        
              [DisplayName("Chapter ID")]      
      [Required]
public int ChapterID { get; set; }
    
              [DisplayName("Articles")]      
      public virtual Article Article { get; set; }
        
              [DisplayName("Chapters")]      
      public virtual Chapter Chapter { get; set; }
    }
}
