//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE4.DbInfrastructure
{
    using System;
    using System.Collections.Generic;
      using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MCQ
    {
        public MCQ()
        {
            this.Questions = new HashSet<Question>();
        }
    
              [DisplayName("MCQ ID")]      
      public int MCQID { get; set; }
        
              [DisplayName("Duration")]      
      [Required]
public short Duration { get; set; }
        
              [DisplayName("Article ID")]      
      [Required]
public long ArticleID { get; set; }
        
              [DisplayName("Title")]      
      [StringLength(150)]
      [Required]
public string Title { get; set; }
        
              [DisplayName("Display Question")]      
      [Required]
public int DisplayQuestion { get; set; }
    
              [DisplayName("Articles")]      
      public virtual Article Article { get; set; }
        
              [DisplayName("Questions")]      
          public virtual ICollection<Question> Questions { get; set; }
    }
}
