//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE4.DbInfrastructure
{
    using System;
    using System.Collections.Generic;
      using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Question
    {
        public Question()
        {
            this.Choices = new HashSet<Choice>();
        }
    
              [DisplayName("Question ID")]      
      public long QuestionID { get; set; }
        
              [DisplayName("Hint")]      
      [StringLength(200)]
     public string Hint { get; set; }
        
              [DisplayName("AnswerChoice ID")]      
      [Required]
public long AnswerChoiceID { get; set; }
        
              [DisplayName("Question Display")]      
      [StringLength(800)]
      [Required]
public string QuestionDisplay { get; set; }
        
              [DisplayName("MCQ ID")]      
      [Required]
public int MCQID { get; set; }
    
              [DisplayName("Choices")]      
      public virtual ICollection<Choice> Choices { get; set; }
        
              [DisplayName("MCQs")]      
      public virtual MCQ MCQ { get; set; }
    }
}
