//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE4.DbInfrastructure
{
    using System;
    using System.Collections.Generic;
      using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.ArticleMistakes = new HashSet<ArticleMistake>();
            this.Bookmarks = new HashSet<Bookmark>();
            this.Ratings = new HashSet<Rating>();
            this.ReplyAgainstMistakes = new HashSet<ReplyAgainstMistake>();
            this.WishLists = new HashSet<WishList>();
        }
    
              [DisplayName("User ID")]      
      public int UserID { get; set; }
        
              [DisplayName("Login Name")]      
      [StringLength(50)]
      [Required]
public string LogName { get; set; }
    
              [DisplayName("Article Name")]      
      public virtual ICollection<ArticleMistake> ArticleMistakes { get; set; }
        
              [DisplayName("Bookmarks")]      
      public virtual ICollection<Bookmark> Bookmarks { get; set; }
        
              [DisplayName("Ratings")]      
      public virtual ICollection<Rating> Ratings { get; set; }
        
              [DisplayName("Reply Against Mistakes")]      
      public virtual ICollection<ReplyAgainstMistake> ReplyAgainstMistakes { get; set; }
        
              [DisplayName("Wish Lists")]      
      public virtual ICollection<WishList> WishLists { get; set; }
    }
}
