//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE4.DbInfrastructure
{
    using System;
    using System.Collections.Generic;
      using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class WatchedReference
    {
              [DisplayName("Watched Reference ID")]      
      public long WatchedReferenceID { get; set; }
        
              [DisplayName("From (Article)")]      
      [Required]
public long WhichFromArticleID { get; set; }
        
              [DisplayName("To (Article)")]      
      [Required]
public long WhichToArticleID { get; set; }
    
        [DisplayName("Articles")]      
        public virtual Article Article { get; set; }
        
        [DisplayName("Articles1")]      
        public virtual Article Article1 { get; set; }
    }
}
