//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE4.DbInfrastructure
{
    using System;
    using System.Collections.Generic;
      using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class WishList
    {
              [DisplayName("WishList ID")]      
      public long WishListID { get; set; }
        
              [DisplayName("User ID")]      
      [Required]
public int UserID { get; set; }
        
              [DisplayName("Article ID")]      
        [Required]
public long ArticleID { get; set; }
        
              [DisplayName("Dated")]      
      [Required]
public System.DateTime Dated { get; set; }
        
              [DisplayName("Last Notified")]      
      [Required]
public System.DateTime LastNotified { get; set; }
    
              [DisplayName("Articles")]      
      public virtual Article Article { get; set; }
        
              [DisplayName("Users")]      
      public virtual User User { get; set; }
    }
}
